version: "2"
services:
  xl-deploy:
    image: xebialabs/xl-deploy:10.2
    container_name: xl-deploy
    ports:
      - "4516:4516"
    environment:
      - ADMIN_PASSWORD=Server@2009
      - ACCEPT_EULA=Y

  xl-release:
    image: xebialabs/xl-release:10.2
    container_name: xl-release
    ports:
      - "5516:5516"
    links:
      - xl-deploy
    environment:
      - ADMIN_PASSWORD=Server@2009
      - ACCEPT_EULA=Y